name: "Releases`"

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix build .#nixlet -o nixlet
    - run: nix build .#nixletNoTpm -o nixlet-no-tpm
    - name: Set release version
      id: vars
      run: |
        version=$(nix eval .#version)
        echo "APP_VERSION=$version" >> $GITHUB_ENV
    - uses: ncipollo/release-action@v1.14.0
      with:
        tag: "${{ env.VERSION }}"
        artifacts: "nixlet,nixlet-no-tpm"
